
name: automate test
on: 
  push:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
      - run: npm run test
      - run: npm run cover




    